### ISSUE TITLE
Improve collapsed sub-process support

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-token-simulation#114]
__What shall we do__

I did update https://github.com/bpmn-io/bpmn-js-token-simulation/pull/87 to build on top of recent token simulation changes. The current state is that it does not break with `bpmn-js@9`, it does not work 100% properly either:

![capture mVi5CJ_optimized](https://user-images.githubusercontent.com/58601/155507512-4435ed65-d204-404f-b694-896ad2e5db2c.gif)

What does not work yet / shall be improved:

* [x] Triggering events / event registration inside sub-process planes broken (https://github.com/bpmn-io/bpmn-js-token-simulation/issues/118)
* [x] Navigation into collapsed sub-process not working (https://github.com/bpmn-io/bpmn-js-token-simulation/issues/188)
* [x] https://github.com/bpmn-io/bpmn-js-token-simulation/issues/135
* [x] No indication that tokens are active inside sub-process => Show them bouncing (cf. token on paused node) on sub-process activity (https://github.com/bpmn-io/bpmn-js-token-simulation/issues/204)
* [ ] Pause icon shows on sub-process plane => Do not show it

----

_Originally posted by @nikku in https://github.com/bpmn-io/bpmn-js-token-simulation/issues/87#issuecomment-1049719321_

**Comment by nikku** [comment]
Closing this with the relevant issues addressed.
